disabled_rules:
  - for_where
  - trailing_comma
  - type_name
  - opening_brace
  - blanket_disable_command
  - identifier_name   # 日本語テスト関数名を仕様書形式で記述しているため除外

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 100
  error: 150

file_length:
  warning: 700
  error: 900

line_length:
  warning: 180
  error: 220
